name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}

    steps:
      - name: ⬇ Git checkout
        uses: actions/checkout@v3

      - name: 💾 Install modules
        run: npm ci

      - name: 🧪 Testing
        run: npm test
